import "@/styles/reset.css"
import "@/styles/global.css";
import Header from "@/components/header"
import Footer from "@/components/footer"

export const metadata = {
  title: "Movie App",
  description: "Generated by create next app",
};

// const interFontFamily = Inter({subsets: ["latin"]})

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className="container">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
